name: Rust

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: cargo test --verbose
